### ISSUE TITLE
Ignore routes option

### ISSUE THREAD

**Issue by pixelpaulaus** [nuxt-modules/html-validator#486]
would be great to have a config option to ignore certain routes.

**Comment by danielroe** [comment]
Good idea!

**Comment by pixelpaulaus** [comment]
i seem to be getting errors now with the update you made....

```
ignore2.test is not a function

at  (./node_modules/@nuxtjs/html-validator/dist/runtime/validator.mjs:48:92)
at Array.some ()
at isIgnored (./node_modules/@nuxtjs/html-validator/dist/runtime/validator.mjs:48:17)
at  (./node_modules/@nuxtjs/html-validator/dist/runtime/nitro.mjs:7:143)
at ./node_modules/hookable/dist/index.mjs:48:66
at Object.run (./node_modules/hookable/dist/index.mjs:41:43)
at ./node_modules/hookable/dist/index.mjs:48:56
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at Object.handler (./node_modules/nitropack/dist/runtime/renderer.mjs:29:5)
at async ./node_modules/h3/dist/index.mjs:1962:19
```

**Comment by danielroe** [comment]
@pixelpaulaus How have you configured it?

**Comment by pixelpaulaus** [comment]
my htmlValidator config in my nuxt config file is empty, nothing there at all. It uses the default values.

**Comment by danielroe** [comment]
Ahh, I see what is causing this. Thanks!

**Comment by danielroe** [comment]
Thanks for the report - should be fixed in the latest release 🤞

**Comment by pixelpaulaus** [comment]
could you help please?....

trying to match any route that starts with /blog/ and  /help/ in the ignore. but it doesn't seem to work...

```
ignore: [
      /^\/blog\//,
      /^\/help\//
    ]
```

how should it look?

**Comment by danielroe** [comment]
I suspect there's just not a trailing slash....? If you have an issue, do create a reproduction 🙏 

If you wish to match `/blog` and also any route that starts with it, the RegExp you'd need is probably `/^\/test(\/|$)/`
